package com.example.auracle.dataholder

import com.example.auracle.R
import com.example.auracle.datapack.listennote.ListenGenre

object FixedData {
    val highLevelGenreList = arrayListOf(
        ListenGenre(125, "History", 67, R.drawable.genre_img_history, "#d0aa3e"),
        ListenGenre(77, "Sports", 67, R.drawable.genre_img_sports, "#E0C9AD"),
        ListenGenre(88, "Health & Fitness", 67, R.drawable.genre_img_health_fitness, "#f9bebc"),
        ListenGenre(93, "Business", 67, R.drawable.genre_img_business, "#344f6d"),
        ListenGenre(122, "Society & Culture", 67, R.drawable.genre_img_society_culture, "#EDDAB5"),
        ListenGenre(127, "Technology", 67, R.drawable.genre_img_technology, "#75D5E2"),
        ListenGenre(132, "Kids & Family", 67, R.drawable.genre_img_kids_family, "#FDBAFB"),
        ListenGenre(168, "Fiction", 67, R.drawable.genre_img_fiction, "#3994d8"),
        ListenGenre(134, "Music", 67, R.drawable.genre_img_music, "#823055"),
        ListenGenre(99, "News", 67, R.drawable.genre_img_news, "#4887F3"),
        ListenGenre(133, "Comedy", 67, R.drawable.genre_img_comedy, "#af9ec0"),
        ListenGenre(100, "Arts", 67, R.drawable.genre_img_arts, "#92aa96"),
        ListenGenre(69, "Religion & Spirituality", 67, R.drawable.genre_img_religion_spirituality, "#A19F83"),
        ListenGenre(68, "TV & Film", 67, R.drawable.genre_img_tv_film, "#EBDACF"),
        ListenGenre(111, "Education", 67, R.drawable.genre_img_education, "#32a057"),
        ListenGenre(107, "Science", 67, R.drawable.genre_img_science, "#7968B6"),
        ListenGenre(135, "True Crime", 67, R.drawable.genre_img_true_crime ,"#362F30"),
    )

    val lowLevelGenreList = arrayListOf(
            ListenGenre(139, "VR & AR"), //, 127),
            ListenGenre(140, "Web Design"), //, 127),
            ListenGenre(142, "English Learning"), //, 116),
            ListenGenre(143, "Programming"), //, 127),
            ListenGenre(144, "Personal Finance"), //, 67),
            ListenGenre(115, "Training"), //, 111),
            ListenGenre(146, "LGBTQ"), //, 122),
            ListenGenre(213, "Daily News"), //, 99),
            ListenGenre(123, "Places & Travel"), //, 122),
            ListenGenre(149, "Venture Capital"), //, 93),
            ListenGenre(138, "Movie"), //, 68),
            ListenGenre(150, "Chinese History"), //, 125),
            ListenGenre(151, "Locally Focused"), //, 67),
            ListenGenre(154, "San Francisco Bay Area"), //, 152),
            ListenGenre(155, "Denver"), //, 152),
            ListenGenre(157, "Startup"), //, 93),
            ListenGenre(158, "NFL"), //, 78),
            ListenGenre(159, "Harry Potter"), //, 68),
            ListenGenre(165, "Storytelling"), //, 122),
            ListenGenre(136, "Crypto & Blockchain"), //, 127),
            ListenGenre(166, "YouTube"), //, 68),
            ListenGenre(83, "Other Games"), //, 82),
            ListenGenre(152, "United States"), //, 151),
            ListenGenre(160, "Star Wars"), //, 68),
            ListenGenre(163, "AI & Data Science"), //, 127),
            ListenGenre(78, "Professional"), //, 77),
            ListenGenre(79, "Outdoor"), //, 77),
            ListenGenre(80, "College & High School"), //, 77),
            ListenGenre(81, "Amateur"), //, 77),
            ListenGenre(90, "Self-Help"), //, 88),
            ListenGenre(109, "Medicine"), //, 107),
            ListenGenre(118, "Local"), //, 117),
            ListenGenre(148, "American History"), //, 125),
            ListenGenre(162, "Game of Thrones"), //, 68),
            ListenGenre(156, "China"), //, 151),
            ListenGenre(147, "SEO"), //, 173),
            ListenGenre(120, "Regional"), //, 117),
            ListenGenre(121, "National"), //, 117),
            ListenGenre(116, "Language Learning"), //, 111),
            ListenGenre(206, "Home & Garden"), //, 82),
            ListenGenre(266, "TV Reviews"), //, 68),
            ListenGenre(153, "New York"), //, 152),
            ListenGenre(137, "NBA"), //, 78),
            ListenGenre(167, "Audio Drama"), //, 122),
            ListenGenre(169, "Sales"), //, 93),
            ListenGenre(164, "Apple"), //, 127),
            ListenGenre(161, "Star Trek"), //, 68),
            ListenGenre(173, "Marketing"), //, 93),
            ListenGenre(125, "History"), //, 67),
            ListenGenre(95, "Business News"), //, 99),
            ListenGenre(219, "Religion"), //, 69),
            ListenGenre(77, "Sports"), //, 67),
            ListenGenre(184, "Drama"), //, 168),
            ListenGenre(88, "Health & Fitness"), //, 67),
            ListenGenre(74, "Other"), //, 69),
            ListenGenre(89, "Fitness"), //, 88),
            ListenGenre(200, "Animation & Manga"), //, 82),
            ListenGenre(93, "Business"), //, 67),
            ListenGenre(145, "Parenting"), //, 132),
            ListenGenre(73, "Judaism"), //, 69),
            ListenGenre(70, "Spirituality"), //, 69),
            ListenGenre(122, "Society & Culture"), //, 67),
            ListenGenre(260, "Wilderness"), //, 77),
            ListenGenre(104, "Books"), //, 100),
            ListenGenre(119, "Non-Profit"), //, 93),
            ListenGenre(131, "Tech News"), //, 99),
            ListenGenre(257, "Swimming"), //, 77),
            ListenGenre(127, "Technology"), //, 67),
            ListenGenre(106, "Fashion & Beauty"), //, 100),
            ListenGenre(175, "Comedy Interviews"), //, 133),
            ListenGenre(195, "Education for Kids"), //, 132),
            ListenGenre(110, "Natural Sciences"), //, 107),
            ListenGenre(262, "After Shows"), //, 68),
            ListenGenre(171, "Entrepreneurship"), //, 93),
            ListenGenre(181, "Self-Improvement"), //, 111),
            ListenGenre(132, "Kids & Family"), //, 67),
            ListenGenre(208, "Music Commentary"), //, 134),
            ListenGenre(108, "Social Sciences"), //, 107),
            ListenGenre(97, "Management"), //, 93),
            ListenGenre(185, "Science Fiction"), //, 168),
            ListenGenre(191, "Mental Health"), //, 88),
            ListenGenre(209, "Music History"), //, 134),
            ListenGenre(248, "Basketball"), //, 77),
            ListenGenre(112, "Educational Technology"), //, 111),
            ListenGenre(168, "Fiction"), //, 67),
            ListenGenre(85, "Video Games"), //, 82),
            ListenGenre(210, "Music Interviews"), //, 134),
            ListenGenre(249, "Cricket"), //, 77),
            ListenGenre(178, "Courses"), //, 111),
            ListenGenre(91, "Alternative Health"), //, 88),
            ListenGenre(134, "Music"), //, 67),
            ListenGenre(237, "Earth Sciences"), //, 107),
            ListenGenre(99, "News"), //, 67),
            ListenGenre(215, "News Commentary"), //, 99),
            ListenGenre(72, "Buddhism"), //, 69),
            ListenGenre(238, "Life Sciences"), //, 107),
            ListenGenre(67, "Podcasts"), //, null),
            ListenGenre(133, "Comedy"), //, 67),
            ListenGenre(87, "Aviation"), //, 82),
            ListenGenre(214, "Entertainment News"), //, 99),
            ListenGenre(239, "Mathematics"), //, 107),
            ListenGenre(100, "Arts"), //, 67),
            ListenGenre(241, "Nature"), //, 107),
            ListenGenre(245, "Relationships"), //, 122),
            ListenGenre(247, "Baseball"), //, 77),
            ListenGenre(105, "Design"), //, 100),
            ListenGenre(190, "Medicine"), //, 88),
            ListenGenre(242, "Physics"), //, 107),
            ListenGenre(101, "Performing Arts"), //, 100),
            ListenGenre(183, "Comedy Fiction"), //, 168),
            ListenGenre(198, "Stories for Kids"), //, 132),
            ListenGenre(69, "Religion & Spirituality"), //, 67),
            ListenGenre(94, "Careers"), //, 93),
            ListenGenre(117, "Government"), //, 67),
            ListenGenre(84, "Automotive"), //, 82),
            ListenGenre(124, "Personal Journals"), //, 122),
            ListenGenre(204, "Games"), //, 82),
            ListenGenre(86, "Hobbies"), //, 82),
            ListenGenre(68, "TV & Film"), //, 67),
            ListenGenre(192, "Nutrition"), //, 88),
            ListenGenre(197, "Pets & Animals"), //, 132),
            ListenGenre(75, "Christianity"), //, 69),
            ListenGenre(82, "Leisure"), //, 67),
            ListenGenre(203, "Crafts"), //, 82),
            ListenGenre(76, "Hinduism"), //, 69),
            ListenGenre(71, "Islam"), //, 69),
            ListenGenre(221, "Astronomy"), //, 107),
            ListenGenre(222, "Chemistry"), //, 107),
            ListenGenre(113, "Higher Education"), //, 111),
            ListenGenre(114, "K-12"), //, 111),
            ListenGenre(103, "Visual Arts"), //, 100),
            ListenGenre(244, "Documentary"), //, 122),
            ListenGenre(126, "Philosophy"), //, 122),
            ListenGenre(98, "Investing"), //, 93),
            ListenGenre(141, "Golf"), //, 77),
            ListenGenre(253, "Hockey"), //, 77),
            ListenGenre(102, "Food"), //, 100),
            ListenGenre(111, "Education"), //, 67),
            ListenGenre(176, "Improv"), //, 133),
            ListenGenre(177, "Stand-Up"), //, 133),
            ListenGenre(217, "Sports News"), //, 99),
            ListenGenre(107, "Science"), //, 67),
            ListenGenre(254, "Rugby"), //, 77),
            ListenGenre(263, "Film History"), //, 68),
            ListenGenre(264, "Film Interviews"), //, 68),
            ListenGenre(265, "Film Reviews"), //, 68),
            ListenGenre(128, "How To"), //, 111),
            ListenGenre(92, "Sexuality"), //, 88),
            ListenGenre(250, "Fantasy Sports"), //, 77),
            ListenGenre(251, "Football"), //, 77),
            ListenGenre(255, "Running"), //, 77),
            ListenGenre(256, "Soccer"), //, 77),
            ListenGenre(258, "Tennis"), //, 77),
            ListenGenre(259, "Volleyball"), //, 77),
            ListenGenre(130, "Gadgets"), //, 127),
            ListenGenre(129, "Podcasting"), //, 127),
            ListenGenre(96, "Shopping"), //, 93),
            ListenGenre(261, "Wrestling"), //, 77),
            ListenGenre(135, "True Crime"), //, 67),
            ListenGenre(216, "Politics"), //, 9)}
    )

}